import { HospitalSummary, DepartmentCrowd } from '../types/crowd';
import { UserProfile } from '../types/auth';
import { Appointment } from '../types/appointment';
import { PatientNotification } from '../types/notification';

export const DEMO_PREVIEW_FLAG_TEXT = 'Demonstration / Preview Data — Supabase database integration ready';

export const MOCK_CITYCARE_PREVIEW: DepartmentCrowd = {
  id: 'dept-citycare-opd-01',
  hospitalId: 'hosp-01',
  hospitalName: 'CityCare Hospital',
  name: 'General OPD',
  code: 'OPD-GEN',
  isOpen: true,
  activeDoctors: 6,
  crowd: {
    level: 'HIGH',
    currentPatients: 82,
    maxCapacity: 100,
    estimatedWaitMinutes: 45,
    recommendation: 'Consider visiting after 5:00 PM.',
    lastUpdated: '2 minutes ago',
    trend: 'increasing',
  },
};

export const MOCK_HOSPITALS: HospitalSummary[] = [
  {
    id: 'hosp-01',
    name: 'CityCare Hospital',
    address: '450 Healthcare Boulevard, Metro District',
    city: 'Metropolis',
    phone: '+1 (555) 019-2834',
    overallCrowdLevel: 'HIGH',
    totalDepartments: 6,
    averageWaitMinutes: 38,
    distanceKm: 2.4,
    operatingHours: '08:00 AM - 08:00 PM',
    isEmergencyAvailable: true,
    departments: [
      MOCK_CITYCARE_PREVIEW,
      {
        id: 'dept-citycare-peds',
        hospitalId: 'hosp-01',
        hospitalName: 'CityCare Hospital',
        name: 'Pediatrics',
        code: 'PED-01',
        isOpen: true,
        activeDoctors: 4,
        crowd: {
          level: 'MODERATE',
          currentPatients: 28,
          maxCapacity: 60,
          estimatedWaitMinutes: 20,
          recommendation: 'Moderate queue. Token registration open.',
          lastUpdated: '5 minutes ago',
          trend: 'stable',
        },
      },
      {
        id: 'dept-citycare-emg',
        hospitalId: 'hosp-01',
        hospitalName: 'CityCare Hospital',
        name: 'Emergency & Triage',
        code: 'EMG-01',
        isOpen: true,
        activeDoctors: 8,
        crowd: {
          level: 'LOW',
          currentPatients: 12,
          maxCapacity: 50,
          estimatedWaitMinutes: 5,
          recommendation: 'Priority access active. Immediate triage available.',
          lastUpdated: '1 minute ago',
          trend: 'decreasing',
        },
      },
      {
        id: 'dept-citycare-ortho',
        hospitalId: 'hosp-01',
        hospitalName: 'CityCare Hospital',
        name: 'Orthopedics & Trauma',
        code: 'ORTH-01',
        isOpen: true,
        activeDoctors: 3,
        crowd: {
          level: 'LOW',
          currentPatients: 14,
          maxCapacity: 45,
          estimatedWaitMinutes: 10,
          recommendation: 'Fast consultation flow available.',
          lastUpdated: '8 minutes ago',
          trend: 'stable',
        },
      },
    ],
  },
  {
    id: 'hosp-02',
    name: 'Metro Health Medical Center',
    address: '128 Innovation Way, North Wing',
    city: 'Metropolis',
    phone: '+1 (555) 018-9900',
    overallCrowdLevel: 'LOW',
    totalDepartments: 4,
    averageWaitMinutes: 12,
    distanceKm: 4.1,
    operatingHours: '24 / 7 Care Center',
    isEmergencyAvailable: true,
    departments: [
      {
        id: 'dept-metro-opd',
        hospitalId: 'hosp-02',
        hospitalName: 'Metro Health Medical Center',
        name: 'General OPD',
        code: 'M-OPD',
        isOpen: true,
        activeDoctors: 5,
        crowd: {
          level: 'LOW',
          currentPatients: 19,
          maxCapacity: 80,
          estimatedWaitMinutes: 12,
          recommendation: 'Optimal time for visit. Minimal delay.',
          lastUpdated: '3 minutes ago',
          trend: 'decreasing',
        },
      },
      {
        id: 'dept-metro-cardio',
        hospitalId: 'hosp-02',
        hospitalName: 'Metro Health Medical Center',
        name: 'Cardiology',
        code: 'M-CARD',
        isOpen: true,
        activeDoctors: 4,
        crowd: {
          level: 'MODERATE',
          currentPatients: 31,
          maxCapacity: 50,
          estimatedWaitMinutes: 25,
          recommendation: 'Prior appointment recommended.',
          lastUpdated: '4 minutes ago',
          trend: 'stable',
        },
      },
    ],
  },
  {
    id: 'hosp-03',
    name: 'Apex SuperSpecialty Hospital',
    address: '77 Westside Boulevard',
    city: 'Metropolis',
    phone: '+1 (555) 017-4422',
    overallCrowdLevel: 'MODERATE',
    totalDepartments: 8,
    averageWaitMinutes: 24,
    distanceKm: 6.8,
    operatingHours: '07:00 AM - 10:00 PM',
    isEmergencyAvailable: true,
    departments: [
      {
        id: 'dept-apex-derma',
        hospitalId: 'hosp-03',
        hospitalName: 'Apex SuperSpecialty Hospital',
        name: 'Dermatology & Skin Care',
        code: 'A-DERM',
        isOpen: true,
        activeDoctors: 3,
        crowd: {
          level: 'MODERATE',
          currentPatients: 24,
          maxCapacity: 40,
          estimatedWaitMinutes: 22,
          recommendation: 'Moderate waiting time. Slot available at 4:30 PM.',
          lastUpdated: '10 minutes ago',
          trend: 'stable',
        },
      },
    ],
  },
];

export const MOCK_PATIENT_USER: UserProfile = {
  id: 'usr-patient-demo',
  email: 'patient@mediq-health.com',
  fullName: 'Sarah Jenkins',
  role: 'patient',
  phone: '+1 (555) 234-5678',
  createdAt: '2026-01-15T09:00:00Z',
};

export const MOCK_HOSPITAL_USER: UserProfile = {
  id: 'usr-hospital-demo',
  email: 'admin@citycare.org',
  fullName: 'Dr. Robert Vance (Op Lead)',
  role: 'hospital',
  hospitalId: 'hosp-01',
  phone: '+1 (555) 987-6543',
  createdAt: '2026-01-10T08:00:00Z',
};

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'usr-patient-demo',
    patientName: 'Sarah Jenkins',
    hospitalId: 'hosp-01',
    hospitalName: 'CityCare Hospital',
    departmentId: 'dept-citycare-opd-01',
    departmentName: 'General OPD',
    appointmentTime: '2026-10-05T10:30:00Z',
    tokenNumber: 42,
    status: 'scheduled',
    estimatedWaitMinutes: 45,
    crowdLevelAtBooking: 'HIGH',
    notes: 'Routine health checkup',
    createdAt: '2026-10-04T14:20:00Z',
  },
  {
    id: 'apt-102',
    patientId: 'usr-patient-demo',
    patientName: 'Sarah Jenkins',
    hospitalId: 'hosp-02',
    hospitalName: 'Metro Health Medical Center',
    departmentId: 'dept-metro-cardio',
    departmentName: 'Cardiology',
    appointmentTime: '2026-10-08T15:00:00Z',
    tokenNumber: 14,
    status: 'scheduled',
    estimatedWaitMinutes: 20,
    crowdLevelAtBooking: 'MODERATE',
    notes: 'Follow-up consultation',
    createdAt: '2026-10-03T11:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS: PatientNotification[] = [
  {
    id: 'notif-01',
    patientId: 'usr-patient-demo',
    type: 'crowd_alert',
    title: 'Crowd Spike Detected at CityCare General OPD',
    message: 'Current waiting time is 45 min (High crowd). We recommend visiting after 5:00 PM to save waiting time.',
    hospitalName: 'CityCare Hospital',
    departmentName: 'General OPD',
    crowdLevel: 'HIGH',
    timestamp: '15 minutes ago',
    isRead: false,
    actionUrl: '/patient/hospitals',
  },
  {
    id: 'notif-02',
    patientId: 'usr-patient-demo',
    type: 'wait_time_update',
    title: 'Token #42 Queue Update',
    message: 'Your estimated consultation time is now 11:15 AM (15 min delay due to surge).',
    hospitalName: 'CityCare Hospital',
    departmentName: 'General OPD',
    crowdLevel: 'HIGH',
    timestamp: '1 hour ago',
    isRead: true,
    actionUrl: '/patient/appointments',
  },
];
